### ISSUE TITLE
CI: cache docker image between runs/jobs

### ISSUE THREAD

**Issue by peppidesu** [PolarExpress/marketplace-backend#11]
Currently, the CI workflow rebuilds the docker image for testing every time. This takes a lot of time, especially since most of the time the docker image doesn't really change at all. 

https://stackoverflow.com/questions/71348621/docker-re-use-container-image-by-caching

This StackOverflow question mentions a way to cache docker containers from previous jobs (and perhaps previous runs?) to speed up the workflow.

**Comment by stickyPiston** [comment]
Since we don't use docker for the ci anymore, we can close this as completed
