### ISSUE TITLE
CI: Testing in docker containers incompatible with coverage artifacts (+ others)

### ISSUE THREAD

**Issue by peppidesu** [PolarExpress/marketplace-backend#14]
There are a few problems with the current CI pipeline, which runs the Jest unit tests inside a docker container.
- We cannot upload the generated coverage reports as artifacts, because they are lost when the docker container exits
- The docker container is slow to build (related: #11)
- The docker container runs `npx zenstack generate`, which adds non-persistent changes to the repo before testing, making testing results unreliable.

We should rewrite the CI pipeline to setup the node environment on the runner, using composite actions.

**Comment by stickyPiston** [comment]
Closing as completed for the same reason as #11
