### ISSUE TITLE
Do not use cached node_modules when schema is modified in workflows

### ISSUE THREAD

**Issue by stickyPiston** [PolarExpress/marketplace-backend#35]
Whenever the prisma schema is changed the ci keeps using the old schema that is cached in the node_modules folder. So we need to detect whether the schema is changed and rerun `npm ci` and `npx prisma generate` (not `npm run gen-schema`, because it tries to write to the database too). This is an issue that arose when trying to merge #33 and we created a quick and dirty solution that needs a more permanent fix.

**Comment by peppidesu** [comment]
solved in #33
